version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres301
      - POSTGRES_USER=postgres301
      - POSTGRES_PASSWORD=postgres301
  web: 
    build: .
    command: python3 manage.py runserver 0.0.0.0:8009
    volumes:
      - ./data
    ports:
      - "8009:8009"
    depends_on:
      - db 
